plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev.legacyforge' version '2.0.140'
}

version = "${minecraft_version}-${mod_version}-release"
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"
legacyForge {
    version = "1.20.1-47.4.0"

    runs {
        client {
            client()

            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
            systemProperty 'forge.enabledGameTestNamespaces', mod_id
            systemProperty 'production', "true"

            if (project.hasProperty('mc_uuid')) {
                jvmArgument "--uuid=${project.getProperty('mc_uuid')}"
            }
            if (project.hasProperty('mc_username')) {
                jvmArgument "--username=${project.getProperty('mc_username')}"
            }
            if (project.hasProperty('mc_accessToken')) {
                jvmArgument "--accessToken=${project.getProperty('mc_accessToken')}"
            }
        }

        server {
            server()

            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
            systemProperty 'forge.enabledGameTestNamespaces', mod_id
            systemProperty 'production', "true"
        }

        gameTestServer {
            server()

            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
            systemProperty 'forge.enabledGameTestNamespaces', mod_id
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {

    maven {
        url "https://maven.latvian.dev/releases"
        content {
            includeGroup "dev.latvian.mods"
        }
    }
    maven {
        url = "https://maven.architectury.dev"
    }
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }

    maven { url = "https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/" }
    maven { url = "https://maven.theillusivec4.top" }
    maven { url = "https://maven.blamejared.com" }
    maven { url = "https://maven.kosmx.dev/" }
    maven {
        name = "Iron's Maven"
        url = "https://code.redspace.io/releases"
    }
    maven {
        name = "Iron's Maven - Snapshots"
        url = "https://code.redspace.io/snapshots"
    }

}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
    config "${mod_id}.mixins.json"
}

dependencies {
    annotationProcessor "org.spongepowered:mixin:${mixin_version}:processor"

    modImplementation "dev.latvian.mods:kubejs-forge:${kubejs_version}"
    modImplementation "dev.latvian.mods:rhino-forge:${rhino_version}"
    modImplementation "dev.architectury:architectury-forge:${architectury_version}"
    modImplementation "top.theillusivec4.curios:curios-forge:${curios_version}"
    modImplementation "io.redspace:irons_spellbooks:${irons_spells_version}:api"
    modImplementation "io.redspace:irons_spellbooks:${irons_spells_version}"
    modCompileOnly "curse.maven:entityjs-967617:${entityjs_file_id}"
    modCompileOnly "software.bernie.geckolib:geckolib-forge-${minecraft_version}:${geckolib_version}"
    modCompileOnly "curse.maven:probejs-585406:5227399"

    modRuntimeOnly "software.bernie.geckolib:geckolib-forge-${minecraft_version}:${geckolib_version}"
    modRuntimeOnly "top.theillusivec4.caelus:caelus-forge:${caelus_version}"
    modRuntimeOnly "dev.kosmx.player-anim:player-animation-lib-forge:${player_animator_version}"
    modRuntimeOnly "curse.maven:entityjs-967617:${entityjs_file_id}"

    modRuntimeOnly "mezz.jei:jei-${jei_mc_version}-forge:${jei_version}"

    modCompileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
    modImplementation(jarJar("io.github.llamalad7:mixinextras-forge:0.4.1"))

    modImplementation "org.reflections:reflections:0.10.2"
    modImplementation "org.javassist:javassist:3.20.0-GA"
}

def resourceTargets = ['META-INF/mods.toml', 'pack.mcmeta']
def replaceProperties = [
        minecraft_version: minecraft_version, minecraft_version_range: minecraft_version_range,
        forge_version: forge_version, forge_version_range: forge_version_range,
        loader_version_range: loader_version_range,
        mod_id: mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
        mod_authors: mod_authors, mod_description: mod_description,
        entityjs_version_range: entityjs_version_range,
        curios_version_range: curios_version_range,
        irons_spellbooks_version_range: irons_spellbooks_version_range,
]
processResources {
    inputs.properties replaceProperties
    replaceProperties.put 'project', project

    filesMatching(resourceTargets) {
        expand replaceProperties
    }
}

jar {
    manifest {
        attributes([
                'Specification-Title': mod_id,
                'Specification-Vendor': mod_authors,
                'Specification-Version': '1',
                'Implementation-Title': project.name,
                'Implementation-Version': mod_version,
                'Implementation-Vendor': mod_authors,
                'Implementation-Timestamp': new Date().format('yyyy-MM-dd\'T\'HH:mm:ssZ')
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs << '-parameters'
}

jar.finalizedBy('reobfJar')

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}
