plugins {
    id "java-library"
    id "idea"
    id "maven-publish"
    id "net.neoforged.moddev" version "2.0.10-beta"
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        url "https://maven.latvian.dev/releases"
        content {
            includeGroup "dev.latvian.mods"
        }
    }
    flatDir {
        dir "libs"
    }
}

base {
    archivesName = mod_id
}

sourceSets {
    main {
        java {}
    }
    test {
        java {
            compileClasspath += sourceSets.main.output
            runtimeClasspath += sourceSets.main.output
        }
    }
}

neoForge {
    // We currently only support NeoForge versions later than 21.0.x
    // See https://projects.neoforged.net/neoforged/neoforge for the latest updates
    version = neo_version
    
    // Validate AT files and raise errors when they have invalid targets
    // This option is false by default, but turning it on is recommended
    validateAccessTransformers = true

    runs {
        gameTestServer {
            server()
            systemProperty "neoforge.enabledGameTestNamespaces", mod_id
        }

        client {
            client()
            systemProperty "neoforge.enabledGameTestNamespaces", mod_id
        }
        data {
            data()
        }
        server {
            server()
            systemProperty "neoforge.enabledGameTestNamespaces", mod_id
        }
    }

    mods {
        testproject {
            sourceSet sourceSets.main
            sourceSet sourceSets.test
        }

    }

//    interfaceInjectionData = files("interfaces.json")

    unitTest {
        // Enable JUnit support in the moddev plugin
        enable()
        // Configure which mod is being tested.
        // This allows NeoForge to load the test/ classes and resources as belonging to the mod.
        testedMod = mods.testproject // <mod name> must match the name in the mods { } block.
    }
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
//    implementation "net.neoforged:neoforge:${neo_version}"

    implementation(accessTransformers(interfaceInjectionData("dev.latvian.mods:kubejs-neoforge:${kubejs_version}")))
//    api "dev.latvian.mods:rhino:2100.2.5-build.41" transitive false

//    implementation "blank:kubejs:2100.7.0-local.1720980467"
    implementation "curse.maven:irons-spells-n-spellbooks-855414:${irons_spellbooks_file_id}"
    runtimeOnly "curse.maven:adorned-1036809:5546365" // curios-neoforge-9.0.5+1.21.0.jar
    runtimeOnly "curse.maven:caelus-308989:5442975" // caelus-neoforge-7.0.0+1.21.jar
    runtimeOnly "curse.maven:geckolib-388172:5605715" // geckolib-neoforge-1.21-4.5.8.jar

//    implementation "blank:productivebees:1.21.0-13.1.1-all"

    runtimeOnly "curse.maven:emi-580555:5619579"
    runtimeOnly "curse.maven:jade-324717:5591256"
//    runtimeOnly "curse.maven:probejs-585406:5536459"

    // compileOnlyApi "blank:productivelib:1.21.0-0.1.2"

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation "net.neoforged:testframework:${neo_version}"
}

test {
    useJUnitPlatform()
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
            irons_spellbooks_version : irons_spellbooks_version,
            kubejs_version         : kubejs_version
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
    project {
        jdkName = "21"
        languageLevel = "21"
    }
}
